# Use root/example as user/password credentials
version: '3.7'

services:

  db:
    image: mysql
    container_name: mysql_server
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    container_name: mysql_client
    restart: always
    ports:
      - 8080:8080