CREATE TABLE LOCATION_TRACK(
   USER_ID VARCHAR(100) NOT NULL,
   TIME_STAMP BIGINT NOT NULL,
   LATITUDE DOUBLE NOT NULL,
   LONGITUDE DOUBLE NOT NULL
)ENGINE=INNODB;

ALTER TABLE LOCATION_TRACK ADD INDEX (USER_ID, TIME_STAMP);